services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    volumes:
      - /docker/adguard-sync/config/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    ports:
      - 8090:8080
    restart: unless-stopped